# Continuous deployment configuration
# See http://doc.gitlab.com/ci/builds_configuration/README.html

variables:
    GOOGLE_API_KEY: AIzaSyChNlerDt3cxNWvSylVdCsUkJ-3l87qojU
    ENVIRONMENT: development

before_script:
    - hostname
    - docker version
    - docker info

build:
    stage: build
    script: make build

lint:
    stage: test
    script: make lint

unit-test:
    stage: test
    script: make unit-test

feature-test:
    stage: test
    script: make feature-test

maps-test:
    stage: test
    script: make maps-test

personalisation-test:
    stage: test
    script: make personalisation-test

# Deploy to test environment when tagged
deploy:
    stage: deploy
    script: make build-prod dockerpush release-dev release-test
    only:
        - tags

dependency_scanning:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]
