#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore: 'src/styles/normalize.scss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 2
  no-debug: 2
  no-ids: 2
  no-important: 2
  hex-length: 0
  no-css-comments: 0
  property-sort-order: 0
  no-important: 0
  no-color-keywords: 0
  no-color-literals: 0
  single-line-per-selector: 0
  nesting-depth: 0
  zero-unit: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 4
  variable-for-property:
    - 0
