language: node_js

script:
    - script/typecheck
    - script/test

addons:
    sauce_connect: true

env:
  global:
    - secure: bwZkTCnLpUgCehOB8qln2m9ju2xyw/GzqbCBNBgsuZtKbQfs63nCe2hDRTYMkot2ceh5SMdcTyyItPU/g17u32x4cJYHQiCSOF9I+c3zSVhK+ZT/YO1uqi7lEyLkugdbYrv0/peA+PYfC1GY5CS7VxNpo5LHmGDbwYM0laUQlc+e+ww6KSdtlGK4o46oDWjjoiODaGPv+tMN5gQJoWRobJqeftl+j56kLhOZwzuL3Kk5JfyqHK2Ea8BvSdKj7b0c37MJQYdDKMOg4D5zuy2u/fEgAo3SYQO8cL+gWhPFIKg+FeEK3K5riLjYqTak3QGAZqVwNHuGxQgsIX1qNNS6+wGNTwWAs9FcnOAa0hOfCgeADyutw13YPrnoO5MJHBiWml5jH2wd3IZ6676ztv6QvWuLSN8JQqSyuyGAHqFVdQ9gQm3K5a6MbeLgNdHYQ02dujs90RQAc874kuIScwuFKEGoWEWwVhlSxlwBGwFh6TLzq4Lz9v2wYpF3p3NXEbgINksrgUS+3YkKn66e+srALZgNSuXF7ts1jbQjfQE1oezp4uMGP86hf/vNE2Zh9kIqJxZOcDw7GbwXu85cKsrC85YgX0pbbleyphmBnk6GvXh3C4UinyHAvSe3sr2yfrcob910hO43TOtZkpjXa69qxGEf2HKSoppzNvPn5mRezKI=
    - secure: YAtD1QNYjoOA89dMsfeWCjasiHwq/1K1SaW+MM9IJWMkASPcyG4A6rvDFNV7L7BteGDJWzRylB5nw80W16PAEHudRP1crM25qwL3UrLsdEVJfX9g8fN20QCKdljS39BeVFHntj0ms5gqIOwSbxKxeac8xRkSXvrcqHKxNg8KPmIH81tlUbnW3pdI/gLhzb4tRMvXSXJi9xcZttuP+bcws5hRnSp8W9gkxIN2wNmsUSpcfqjMPdNWUjYWpF36elGbd3GJKvCowKUwsHsE4q53BhVMsx3UQcE1LPuf4AVl6HSu3ZvBAgmi4bqnoXq6Ak9eq44+e/IPMoTB7gAt2/jY3LXDOX+efe+rUa9ZJekExycPsSUaRVfyTCPE9XmcI6X0cfEqvI0d7h4AajYWqAyS2aL2b0zpic2TOUFV56OngszZCi5x/WfJdolWnJ2xS9Ito4KCf+d1Ec8Y5Q7YPOvtmTDFBHixwRLwaBR4AhjRlNDd4exzAsV/Rg9hwpMVp+FL+zNZyk/WNNQWDDRm5p+/3MANF/WRUV+xKfgio+A7tNZeCDEQCJT0Y0dIhp+azEmBSIts7ZC13i91tDlKYXzvl78vHc1ShyLVjogSVpZi7wZngDItcIqEchFXC6zFo/YNwDX3/WaxaH48TMVRm9krcWtLXua9sgWUWZArWbUa1w0=

  matrix:
    - SELENIUM_BROWSER=firefox
    - SELENIUM_BROWSER=chrome
